name: 'Update conan dependants in organization'
description: 'Update conan dependants in organization repositories'
author: 'FreePhoenix888'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  organizationName:
    required: true
    description: 'The name of the organization whose repositories must be updated to change the conan dependency version.'
  token:
    required: true
    description: 'The github access token'
  conanFilePath:
      required: true
      description: 'The path of the conanfile.txt in organization repositories.'
  commitMessageTemplate:
      required: true
      description: 'The commit message that will be used to update conanfile.txt. Template variables can be used with the folowwing syntax: {TEMPLATE_VARIABLE} and will be replaced with the corresponding value. Template variables: PREVIOUS_VERSION - the previous version of the package in the  conanfile.txt of the dependant package; the conanFileReplaceableRegex must contain named capture group with the name PREVIOUS_VERSION to use this template variable.'
  sourceBranchName:
      required: true
      description: 'The name of the branch that will be taken as the basis.'
  destinationBranchName:
      required: true
      description: 'The name of the branch that will be used to publish the new commit.'
  conanFileReplaceableRegex:
      required: true
      description: 'The regex that will be replaced in the conanfile.txt. Can contain PREVIOUS_VERSION named capture group if the commitMessageTemplate contains the PREVIOUS_VERSION template variable.'
  conanFileReplacement:
      required: true
      description: 'The text that will be inserted instead of the replaceable regex.'
  shouldOpenPullRequest:
      required: false
      default: "true"
      description: 'true or false value that determines whether the pull request should be opened. Redundant if the destination branch name is the same as the source branch name.'
  pullRequestTitle:
      required: false
      description: 'The title of the pull request that will be opened.'
  pullRequestBody:
    required: true
    description: 'The body of the pull request that will be opened.'

runs:
  using: 'node16'
  main: 'dist/index.js'
